:bookmark: release v0.9.7
bioinformatics-ptp/detectRUNS pull request #28
Opened 2022-01-05 18:06 UTC by filippob

Improving the output of the function `tableRuns`

## Description

On the `devel` branch, the code of the function `tableRuns` has been modified to add a column named `avg_pct` to the output dataframe

## Related Issue

close #43 
close #39 
close #31 
close #36 
close #17 

## Motivation and Context

It adds a piece of relevant information to the output of the function `tableRuns` (ROH/HRR islands)

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-05-09 15:57 UTC, filippob commented
Ready to merge for me

2023-05-25 15:17 UTC, bunop requested changes
I think that issue #41 should be addressed before merging

2023-05-25 15:17 UTC, bunop commented on detectRUNS/R/Stats.R
> +#' 1) summary_ROH_count_chr: n. of runs per chromosome and breed/group;
This list will be rendered as a plain text. Consider using [list with roxygen](https://roxygen2.r-lib.org/articles/formatting.html#lists), for example:
```R
#' \enumerate{
#'  \item{summary_ROH_count_chr: }{n. of runs per chromosome and breed/group}
#'  \item{summary_ROH_percentage_chr: }{percent distribution of runs per chromosome in each breed/group (sum to 1)}
#'  \item{summary_ROH_count: }{n. of runs per size-class (Mb) in each breed/group}
#' <add all the other items>
#' }
```

2023-05-25 15:17 UTC, bunop commented on detectRUNS/R/Stats.R
> +#' 9) result_Froh_class: genome-wide inbreeding ($F_{ROH}$) for each individual in the dataset per size-class (Mb) of runs
There could be a 10th item when providing `snpInRuns=TRUE` as parameter

2023-05-25 15:17 UTC, bunop commented on detectRUNS/R/run.R
> +#' @param mapFile map file (.map) file path (chromosomes should be numeric)
will be better to check chromosomes in `readMapFile` directly and throw an error here?

2026-05-28 16:27 UTC, merged